apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-dzo8
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-dzo8
    app.kubernetes.io/part-of: load-app-d5c4aab4-f208-44bf-aaf9-959c9843bf15
  name: devfile-sample-dzo8
spec:
  ports:
  - port: 3001
    targetPort: 3001
  selector:
    app.kubernetes.io/instance: devfile-sample-dzo8
status:
  loadBalancer: {}
